import Head from 'next/head';
import { Inter } from '@next/font/google';
import styled from 'styled-components';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MY BRAND</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StyledButton>Hello</StyledButton>
    </>
  );
}

const StyledButton = styled.button`
  background-color: ${({ theme }) => theme.colors.yellow};
  color: white;
  border: none;
  border-radius: 10px;
  padding: 10px 20px;
  font-size: 1.2rem;
  font-weight: 600;
  &:hover {
    background-color: #d9663;
    color: black;
    cursor: pointer;
  }
`;
